### ISSUE TITLE
Use taggy in a docker enviroment

### ISSUE THREAD

**Issue by torwag** [julianthome/taggy#1]
Hi,
I 'm looking how to use taggy in a nextcloud installation based on docker.
I run a maria-db container together with a nextcloud container. I guess the clean way would be to run taggy as an own container.
However, it seem right now taggy supports only to be installed on the same machine beside nextcloud and the database. 

Any information would be helpful.

**Comment by julianthome** [comment]
Hi Torwag,

I have added parameters for database host and port -- it should be possible know to run taggy on an extra container.

Best,
  Julian
